=== sebas-1106/mejoresPeliculas/XML/configServidor/conf_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="configuracion_servidor">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="base_datos" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="usuario" type="xsd:string"></xsd:element>
                            <xsd:element name="password" type="xsd:string"></xsd:element>
                            <xsd:element name="puerto">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:int">
                                        <xsd:minInclusive value="1024"></xsd:minInclusive>
                                        <xsd:maxExclusive value="65535"></xsd:maxExclusive>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="max_conexiones" type="xsd:int"></xsd:element>
                            <xsd:element name="modo_acceso" >
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="local"></xsd:enumeration>
                                        <xsd:enumeration value="remoto"></xsd:enumeration>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="nombre" type="xsd:string"></xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="backups">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ruta" type="xsd:string"></xsd:element>
                            <xsd:element name="frecuencia">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="diaria"></xsd:enumeration>
                                        <xsd:enumeration value="semanal"></xsd:enumeration>
                                        <xsd:enumeration value="mensual"></xsd:enumeration>
                                    </xsd:restriction>
                                </xsd:simpleType>                            
                            </xsd:element>                        
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>                
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
<!-- XSD para validar nuestro XML: 
    - nombre debe ser un atributo de base de datos


    - puerto debe ser un nÃºmero entre 1024 y 65535

    
    - modo de acceso solo puede ser "local" o "remoto"
    - frecuencia solo puede ser "diaria", "semanal" o "mensual"
-->

=== sebas-1106/mejoresPeliculas/XML/configServidor/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML con la configuraci칩n del servidor.

configuracion_servidor:
  |__ base_datos
  |__ backups

base_datos debe incluir:
    - nombre de la base de datos (atributo)
    - usuario
    - contrase침a
    - puerto
    - m치ximo de conexiones
    - modo de acceso

- seccion de backups que contenga a su vez: 
    - ruta
    - frecuencia
-->
<configuracion_servidor
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="conf_schema.xsd"
>
  <!-- Configuraci칩n para la base de datos de pruebas-->
  <base_datos nombre="BD_Pruebas">
    <usuario>pepe</usuario>
    <password> <![CDATA[admin1234]]></password>
    <puerto>3000</puerto>
    <max_conexiones>1000</max_conexiones>
    <modo_acceso>remoto</modo_acceso>
  </base_datos>
  <base_datos nombre="BD_Proteccion">
    <usuario>pepe</usuario>
    <password> <![CDATA[admin1234]]></password>
    <puerto>3024</puerto>
    <max_conexiones>1000</max_conexiones>
    <modo_acceso>remoto</modo_acceso>
  </base_datos>
  <backups>
    <ruta>/var/backup</ruta>
    <frecuencia>semanal</frecuencia>
  </backups>
</configuracion_servidor>
